version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-user
      MONGO_INITDB_ROOT_PASSWORD: root-password
      MONGO_INITDB_DATABASE: url-shortener
      MONGO_INITDB_USERNAME: test-user
      MONGO_INITDB_PASSWORD: test-password
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
volumes:
  mongodb_data_container:

