version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: db-user
      MONGO_INITDB_ROOT_PASSWORD: db-password
      MONGO_INITDB_DATABASE: url-shortener
      MONGO_INITDB_USERNAME: test-user
      MONGO_INITDB_PASSWORD: test-password
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data_container:

